### ISSUE TITLE
Paths with non-ASCII characters are not handled well on Windows with non-UTF codepage

### ISSUE THREAD

**Issue by optout21** [mikroncoin/lmdb#1]
On Windows OS with non-UTF code page (e.g. Hungarian language Windows), paths with non-ASCII characters are not handled properly, and DB files cannot be opened.

In such case paths are transformed using MultiByteToWideChar() (within utf8_to_utf16()), but always with the CP_UTF8 codepage.  The CreateFileW() API call does not handle this path, if the local codepage is not UTF8.  Correct would be using CP_ACP, which is the system default Windows ANSI code page (see https://docs.microsoft.com/en-us/windows/desktop/api/stringapiset/nf-stringapiset-multibytetowidechar).

In the mikron_node project, this causes a startup failure, see:
https://github.com/mikroncoin/mikron_node/issues/33

**Comment by catenocrypt** [comment]
See pull request #2.

**Comment by optout21** [comment]
See pull request #3

**Comment by optout21** [comment]
Solved, commit 6e342a9a868572df0c08d0934d1e9c94dac8efab, branch lmdb_0_9_21_mikron
